site_name: CASTEP Docs
nav:
   - Home: 'index.md'
   - 'Documentation':
      - 'Getting Started':
        - 'Introduction': 'documentation/Getting_Started/intro.md'
        - 'Command line help': 'documentation/Getting_Started/built_in_help.md'
        - 'Running CASTEP': 'documentation/Getting_Started/running_castep.md'
        - 'cell File': 'documentation/Getting_Started/basic_cell_file.md'
        - 'param File': 'documentation/Getting_Started/basic_param_file.md'
        - 'Checkpoint and Restart': 'documentation/Getting_Started/restarting.md'
      - 'Ground State':
        - 'Overview':  'documentation/Groundstate/intro.md'
        - 'Dispersion Corrections': 'documentation/Groundstate/dftd.md'
        - 'Spin Orbit Coupling': 'documentation/Groundstate/soc.md'
        - 'Spin Constraints': 'documentation/Groundstate/spin_constraints.md'
        - 'Population analysis': 'documentation/Groundstate/population_analysis.md'
        - 'ELF': 'documentation/Groundstate/ELF.md'
      - 'Geometry Optimisation':
        - 'Overview': 'documentation/Geometry_Optimisation/overview.md'
        - 'Keywords': 'documentation/Geometry_Optimisation/keywords.md'
        - 'Constraints': 'documentation/Geometry_Optimisation/constraints.md'
        - 'Files': 'documentation/Geometry_Optimisation/files.md'
        - 'Tools': 'documentation/Geometry_Optimisation/tools.md'
      - 'Molecular Dynamics':
        - 'MD Overview': 'documentation/Molecular_Dynamics/overview.md'
        - 'MD Basics': 'documentation/Molecular_Dynamics/basics.md'
        - 'MD Restarts': 'documentation/Molecular_Dynamics/restarts.md'
        - 'MD Files': 'documentation/Molecular_Dynamics/files.md'
        - 'MD Keywords': 'documentation/Molecular_Dynamics/keywords.md'
        - 'MD Tools': 'documentation/Molecular_Dynamics/tools.md'
        - 'PIMD': 'documentation/Molecular_Dynamics/pimd.md'
        - 'Hugoniostat': 'documentation/Molecular_Dynamics/hugoniostat.md'
      - 'Transition State Search':
        - 'Nudged elastic band': 'documentation/Transition_State_Search/neb.md'
      - 'Exchange-Correlation (XC)':
        - 'Overview': 'documentation/XC/XCoverview.md'
        - 'Controlling XC': 'documentation/XC/XC.md'
        - 'libXC': 'documentation/XC/libXC.md'
      - 'Spectral':
        - 'Overview': 'documentation/Spectral/overview.md'
        - 'Keywords': 'documentation/Spectral/keywords.md'
        - 'Restarts': 'documentation/Spectral/restarts.md'
      - 'Vibrations':
        - 'Vibrations': 'documentation/Vibrations/overview.md'
      - 'NMR':
        - 'NMR Overview': 'documentation/NMR/NMR_overview.md'
      - 'EPR':
        - 'EPR Overview': 'documentation/EPR/overview.md'
      - 'XRD': 'documentation/XRD/overview.md'
      - 'TDDFT':
        - 'TDDFT Overview': 'documentation/TDDFT/overview.md'
      - 'Delta SCF':
        - 'Delta SCF Overview': 'documentation/Delta_SCF/overview.md'
        - 'Simple Delta SCF': 'documentation/Delta_SCF/simple_delta_scf.md'
        - 'Linear expansion DeltaSCF': 'documentation/Delta_SCF/lin_ex_delta_scf.md'
        - 'MO Delta SCF': 'documentation/Delta_SCF/mo_delta_scf.md'
        - 'Molecular Projected DOS': 'documentation/Delta_SCF/molpdos.md'
      - 'DFT+U':
        - 'DFT+U - Theory': 'documentation/DFT+U/dftu-theory.md'
        - 'DFT+U - Input' : 'documentation/DFT+U/dftu-input.md'
        - 'U from Linear Response - Theory': 'documentation/DFT+U/alpha-theory.md'
        - 'U from Linear Response - Input': 'documentation/DFT+U/alpha-input.md'
        - 'U from Linear Response - Output': 'documentation/DFT+U/alpha-output.md'
        - 'U from Linear Response - Warnings/Errors': 'documentation/DFT+U/alpha-warnings-errors.md'
      - 'Pseudopotentials':
        - 'Theory':   'documentation/Pseudopotentials/theory.md'
        - 'Overview': 'documentation/Pseudopotentials/overview.md'
        - 'Headers': 'documentation/Pseudopotentials/reading_headers.md'
        - 'OTFG string': 'documentation/Pseudopotentials/otfg_string.md'
      - 'Input Files':
        - 'cell file':  'documentation/Input_Files/cell_file.md'
        - 'param file': 'documentation/Input_Files/param_file.md'
        - 'cell keywords': 'documentation/Input_Files/cell_keywords.md'
        - 'output files': 'documentation/Input_Files/output_files.md'
      - 'Tools':
        - 'Third Party Tools': 'documentation/Tools/tools.md'
      - 'Troubleshooting':
        - 'Common errors':  'documentation/Troubleshooting/troubleshooting.md'
        - 'Linux help':  'documentation/Troubleshooting/linux_path.md'
   - 'Tutorials':
      - 'Bonding and Charge':
        - 'Plotting Charge Density': 'tutorials/Bonding_and_Charge/charge_density.md'
        - 'Population Analysis': 'tutorials/Bonding_and_Charge/mulliken_population.md'
      - 'Bands and DOS':
        - 'Plotting - CASTEP tools': 'tutorials/Bands_and_DOS/plotting_perl.md'
        - 'Plotting - SUMO': 'tutorials/Bands_and_DOS/plotting_sumo.md'
        -  'Semiconductors':      'tutorials/Bands_and_DOS/semiconductors.md'
        -  'Metals':      'tutorials/Bands_and_DOS/metals.md'
        -  'Magnetic Materials':      'tutorials/Bands_and_DOS/magnetic.md'
      - 'Dispersion corrections': 'tutorials/dispersion_corrections/castep-ase-dispersion-tutorial.md'
      - 'Nudged elastic band': 'tutorials/NEB/neb_tutorial.md'
      - 'NMR Shielding':
        - 'Introduction': 'tutorials/NMR/NMR_shielding.md'
        - 'Inorganic': 'tutorials/NMR/NMR_silicate.md'
        - 'Molecular Crystals': 'tutorials/NMR/NMR_molcrystal.md'
        - 'J coupling': 'tutorials/NMR/NMR_shielding.md'
      - 'Delta SCF':
        - 'Simple Delta SCF': 'tutorials/Delta_SCF/simple_delta_scf.md'
        - 'Linear expansion DeltaSCF': 'tutorials/Delta_SCF/lin_ex_delta_scf.md'
        - 'Molecular Projected DOS': 'tutorials/Delta_SCF/molpdos.md'
      - 'Tools':
        - 'Elastic Constants': 'tutorials/Tools/elastic_constants.md'
   - 'Developer':
      - 'Using Devel Codes': 'developer/using_devel_codes.md'
      - 'Adding empirical potentials': 'developer/adding_pair_pots.md'
      - 'Style Guide': 'developer/style_guide.md'
      - 'Testing': 'developer/adding_testing.md'
      - 'Git workflow': 'developer/git_workflow.md'

theme:
  name: material
  features:
    -content.code.annotate
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
markdown_extensions:
  - admonition
  - def_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - footnotes
extra_css:
  - stylesheets/extra.css
plugins:
  - search
  - bibtex:
      # `bib_file` takes precedence over `bib_dir`, if `bib_file` is defined,
      # the bibtex plugin will use an absolute path to the file, meaning that
      # we can only execute `mkdocs build` in the folder `REPO_root/docs`.
      # With `bib_dir` the bibtex plugin will use a relative path to the
      # `mkdocs.yml` file, and search recursively for all the bib files.
      # Therefore, it is possible to execute `mkdocs build` in both the
      # `REPO_root` and the `REPO_root/docs` folder, then readthedocs can build
      # the docs (since readthedocs always builds the docs in the `REPO_root`).
      bib_file: refs.bib
      # default "{number}", to avoid conflict with user-defined footnotes
      footnote_format: "ref{number}"

